Translated to Maithili language
AndrGab/medirepoWeb pull request #131
Opened 2022-10-20 09:16 UTC by anupeshverma

2022-10-21 01:15 UTC, AndrGab requested changes
Thank you for your time.
Can you add Maithili to i18n.js file?
https://github.com/anupeshverma/medirepoWeb/blob/c93457f651fc060cecead3c535d764ac6ab340b4/src/i18n.js
thanks

2022-10-21 07:14 UTC, anupeshverma commented
Done 
I have added  Maithili to i18n.js file

2022-10-22 08:19 UTC, AndrGab approved these changes

2022-10-22 08:20 UTC, AndrGab approved these changes
good job

2022-10-22 08:21 UTC, merged