Notify user to enter required inputs in login form
AndrGab/medirepoWeb pull request #135
Opened 2022-10-22 18:58 UTC by jayesh-choudhary

2022-10-22 19:05 UTC, jayesh-choudhary commented
@AndrGab can you please review

2022-10-24 00:05 UTC, AndrGab requested changes

2022-10-24 00:05 UTC, AndrGab commented on src/pages/patients/Login.js
> +      setIsFormInComplete(true);
```suggestion
toast.warning(t('fillRequiredFields'));
```
We use toasts, maybe a new toast  should follow the same pattern in application

2022-10-24 00:05 UTC, AndrGab commented on src/pages/patients/Login.js
> +
if you use toast, you can remove these updates too

2022-10-25 11:15 UTC, jayesh-choudhary commented
@AndrGab Comments addressed

2022-10-26 00:53 UTC, AndrGab approved these changes
thanks. good job

2022-10-26 00:54 UTC, merged