[Docs] Added Sinhalese translation
AndrGab/medirepoWeb pull request #149
Opened 2022-10-31 15:22 UTC by Ln11211

Hello,
This PR is related to issue https://github.com/AndrGab/medirepoWeb/issues/76 . Sinhalese is the language of Sri Lanka , I have noticed that the translation is missing, so I have added the Sinhalese translation, hope this helps :)

2022-10-31 15:23 UTC, Ln11211 commented
hey @AndrGab , do you like it? :)

2022-10-31 16:43 UTC, Ln11211 commented
hi @AndrGab , I fixed a typo in Telugu file, it's just a small one, and apart form that, can you please review and merge this PR?

2022-11-03 00:25 UTC, AndrGab requested changes

2022-11-03 00:25 UTC, AndrGab commented on src/i18n.js
> +import contentSl from './locales/si/content.json';
```suggestion
import contentSi from './locales/si/content.json';
```

2022-11-03 00:25 UTC, AndrGab commented on src/locales/si/si.json
> +{
the filename has to be "content.json"

2022-11-03 00:25 UTC, AndrGab approved these changes

2022-11-03 00:26 UTC, merged